spring.application.name=sistema-medico
spring.datasource.url=jdbc:postgresql://sistemamedi.postgres.database.azure.com:5432/sistema_medico?sslmode=require
spring.datasource.username=sistemamedico
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true